name: Publish release

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ["Package executable with PyInstaller - Linux", "Package exe with PyInstaller - Windows"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Get Linux release
      uses: actions/download-artifact@v3
      with:
        name: scorepostgenerator
        path: ./bin

    - name: Get Windows release
      uses: actions/download-artifact@v3
      with:
        name: artifact-from-workflow-2
        path: ./bin

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/scorepostgenerator-*.zip"