name: Package executable with PyInstaller - Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PyInstaller Linux
      uses: NoelleTGS/pyinstaller-action-linux@python3.10
      with:
        path: .

    - uses: actions/upload-artifact@v4
      with:
        name: scorepostgenerator
        path: ./dist/linux