name: Package exe with PyInstaller - Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: PyInstaller Windows
      uses: NoelleTGS/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v4
      with:
        name: scorepostgenerator
        path: ./dist/windows

  package:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Get binary
        uses: actions/download-artifact@v4
        with:
          name: scorepostgenerator
          path: ./dist/windows

      - name: Package release
        run: |
          Copy-Item -Path .\.example.env -Destination .\dist\windows\
          Compress-Archive -Path .\dist\windows\* -DestinationPath .\dist\windows\scorepostgenerator-windows.zip
        shell: pwsh

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: scorepostgenerator
          path: ./dist/windows/scorepostgenerator-windows.zip